name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
      - name: Set up latest Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.5
      - name: Configure git
        run: git config user.name "GitHub Actions" && git config user.email "actions@users.noreply.github.com"

      - name: Release with Gradle
        run: ./gradlew build release -Prelease.useAutomaticVersion=true -PnufinArtifactoryUser=${{ secrets.nufinArtifactoryUser }} -PnufinArtifactoryPassword=${{ secrets.nufinArtifactoryPassword }}